/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avicia_api_util_jni_image_ImageProcessorNative */

#ifndef _Included_com_avicia_api_util_jni_image_ImageProcessorNative
#define _Included_com_avicia_api_util_jni_image_ImageProcessorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avicia_api_util_jni_image_ImageProcessorNative
 * Method:    openclInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_avicia_api_util_jni_image_ImageProcessorNative_openclInit
  (JNIEnv *, jclass);

/*
 * Class:     com_avicia_api_util_jni_image_ImageProcessorNative
 * Method:    processImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFLcom/avicia/api/util/jni/image/ImageProcessorNative/ProcessResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_avicia_api_util_jni_image_ImageProcessorNative_processImage
  (JNIEnv *, jclass, jstring, jstring, jfloat, jfloat, jobject);

/*
 * Class:     com_avicia_api_util_jni_image_ImageProcessorNative
 * Method:    reduceNoise
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILcom/avicia/api/util/jni/image/ImageProcessorNative/ProcessResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_avicia_api_util_jni_image_ImageProcessorNative_reduceNoise
  (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     com_avicia_api_util_jni_image_ImageProcessorNative
 * Method:    openclCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_avicia_api_util_jni_image_ImageProcessorNative_openclCleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
