// kernels.h
// Definições dos kernels OpenCL

#include <stdio.h>
#ifndef KERNELS_H
#define KERNELS_H

// Kernel de processamento de imagem com contraste, brilho e saturação
static const char* processImageKernel = 
"// Conversão RGB para HSV\n"
"inline float3 rgb_to_hsv(float3 rgb) {\n"
"    float cmax = fmax(fmax(rgb.x, rgb.y), rgb.z);\n"
"    float cmin = fmin(fmin(rgb.x, rgb.y), rgb.z);\n"
"    float delta = cmax - cmin;\n"
"    \n"
"    float h = 0.0f;\n"
"    if (delta > 0.00001f) {\n"
"        if (cmax == rgb.x) {\n"
"            h = 60.0f * fmod((rgb.y - rgb.z) / delta, 6.0f);\n"
"        } else if (cmax == rgb.y) {\n"
"            h = 60.0f * (((rgb.z - rgb.x) / delta) + 2.0f);\n"
"        } else {\n"
"            h = 60.0f * (((rgb.x - rgb.y) / delta) + 4.0f);\n"
"        }\n"
"    }\n"
"    if (h < 0.0f) h += 360.0f;\n"
"    \n"
"    float s = (cmax > 0.00001f) ? (delta / cmax) : 0.0f;\n"
"    float v = cmax;\n"
"    \n"
"    return (float3)(h, s, v);\n"
"}\n"
"\n"
"// Conversão HSV para RGB\n"
"inline float3 hsv_to_rgb(float3 hsv) {\n"
"    float h = hsv.x;\n"
"    float s = hsv.y;\n"
"    float v = hsv.z;\n"
"    \n"
"    float c = v * s;\n"
"    float x = c * (1.0f - fabs(fmod(h / 60.0f, 2.0f) - 1.0f));\n"
"    float m = v - c;\n"
"    \n"
"    float3 rgb_prime;\n"
"    if (h < 60.0f) {\n"
"        rgb_prime = (float3)(c, x, 0.0f);\n"
"    } else if (h < 120.0f) {\n"
"        rgb_prime = (float3)(x, c, 0.0f);\n"
"    } else if (h < 180.0f) {\n"
"        rgb_prime = (float3)(0.0f, c, x);\n"
"    } else if (h < 240.0f) {\n"
"        rgb_prime = (float3)(0.0f, x, c);\n"
"    } else if (h < 300.0f) {\n"
"        rgb_prime = (float3)(x, 0.0f, c);\n"
"    } else {\n"
"        rgb_prime = (float3)(c, 0.0f, x);\n"
"    }\n"
"    \n"
"    return (float3)(rgb_prime.x + m, rgb_prime.y + m, rgb_prime.z + m);\n"
"}\n"
"\n"
"__kernel void processImage(\n"
"    __global const uchar4* input,\n"
"    __global uchar4* output,\n"
"    const int width,\n"
"    const int height,\n"
"    const float contrastFactor,\n"
"    const float brightnessFactor,\n"
"    const float saturationFactor)\n"
"{\n"
"    int x = get_global_id(0);\n"
"    int y = get_global_id(1);\n"
"    if (x >= width || y >= height) return;\n"
"    \n"
"    int idx = y * width + x;\n"
"    uchar4 pixel = input[idx];\n"
"    \n"
"    // Normalizar [0, 1]\n"
"    float3 rgb = (float3)(\n"
"        (float)pixel.x / 255.0f,\n"
"        (float)pixel.y / 255.0f,\n"
"        (float)pixel.z / 255.0f\n"
"    );\n"
"    \n"
"    // 1. Saturação\n"
"    float3 hsv = rgb_to_hsv(rgb);\n"
"    hsv.y = clamp(hsv.y * saturationFactor, 0.0f, 1.0f);\n"
"    rgb = hsv_to_rgb(hsv);\n"
"    \n"
"    // 2. Contraste\n"
"    rgb = (rgb - 0.5f) * contrastFactor + 0.5f;\n"
"    \n"
"    // 3. Brilho\n"
"    rgb = rgb + brightnessFactor;\n"
"    \n"
"    // Clampar e converter\n"
"    pixel.x = (uchar)(clamp(rgb.x, 0.0f, 1.0f) * 255.0f);\n"
"    pixel.y = (uchar)(clamp(rgb.y, 0.0f, 1.0f) * 255.0f);\n"
"    pixel.z = (uchar)(clamp(rgb.z, 0.0f, 1.0f) * 255.0f);\n"
"    \n"
"    output[idx] = pixel;\n"
"}\n";

// Kernel de redução de ruído
static const char* reduceNoiseKernel =
"__kernel void reduceNoise(\n"
"    __global const uchar4* input,\n"
"    __global uchar4* output,\n"
"    const int width,\n"
"    const int height,\n"
"    const int kernelSize)\n"
"{\n"
"    int x = get_global_id(0);\n"
"    int y = get_global_id(1);\n"
"    if (x >= width || y >= height) return;\n"
"    \n"
"    int halfKernel = kernelSize / 2;\n"
"    int sumR = 0, sumG = 0, sumB = 0, sumA = 0;\n"
"    int count = 0;\n"
"    \n"
"    for (int dy = -halfKernel; dy <= halfKernel; dy++) {\n"
"        for (int dx = -halfKernel; dx <= halfKernel; dx++) {\n"
"            int nx = x + dx;\n"
"            int ny = y + dy;\n"
"            \n"
"            if (nx >= 0 && nx < width && ny >= 0 && ny < height) {\n"
"                uchar4 p = input[ny * width + nx];\n"
"                sumR += p.x; sumG += p.y; sumB += p.z; sumA += p.w;\n"
"                count++;\n"
"            }\n"
"        }\n"
"    }\n"
"    \n"
"    int c = (count > 0) ? count : 1;\n"
"    uchar4 result;\n"
"    result.x = (uchar)(sumR / c);\n"
"    result.y = (uchar)(sumG / c);\n"
"    result.z = (uchar)(sumB / c);\n"
"    result.w = (uchar)(sumA / c);\n"
"    output[y * width + x] = result;\n"
"}\n";

// Kernel de estatísticas
static const char* calculateStatsKernel =
"__kernel void calculateStats(\n"
"    __global const float* data,\n"
"    __global float* groupResults,\n"
"    const int n,\n"
"    __local float* localMem)\n"
"{\n"
"    int gid = get_global_id(0);\n"
"    int lid = get_local_id(0);\n"
"    int groupSize = get_local_size(0);\n"
"    int groupId = get_group_id(0);\n"
"\n"
"    float v = (gid < n) ? data[gid] : 0.0f;\n"
"    float* localSum = localMem;\n"
"    float* localMax = localMem + groupSize;\n"
"    float* localMin = localMem + 2 * groupSize;\n"
"\n"
"    localSum[lid] = (gid < n) ? v : 0.0f;\n"
"    localMax[lid] = (gid < n) ? v : -INFINITY;\n"
"    localMin[lid] = (gid < n) ? v : INFINITY;\n"
"\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    for (int stride = groupSize / 2; stride > 0; stride /= 2) {\n"
"        if (lid < stride) {\n"
"            localSum[lid] += localSum[lid + stride];\n"
"            localMax[lid] = fmax(localMax[lid], localMax[lid + stride]);\n"
"            localMin[lid] = fmin(localMin[lid], localMin[lid + stride]);\n"
"        }\n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"    }\n"
"\n"
"    if (lid == 0) {\n"
"        int outIdx = groupId * 3;\n" 
"        groupResults[outIdx + 0] = localSum[0];\n"
"        groupResults[outIdx + 1] = localMax[0];\n" 
"        groupResults[outIdx + 2] = localMin[0];\n"
"    }\n"
"}\n";

// Função para concatenar todos os kernels
static inline char* get_all_kernels() {
    static char combined[65536]; // 64KB buffer
    snprintf(combined, sizeof(combined), "%s\n%s\n%s", 
             processImageKernel, 
             reduceNoiseKernel, 
             calculateStatsKernel);
    return combined;
}

#endif // KERNELS_H