services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: teste_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/roles.sql:/docker-entrypoint-initdb.d/roles.sql
      - ./database/insert.sql:/docker-entrypoint-initdb.d/insert.sql